// Created by iWeb 3.0.4 local-build-20130318

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,35),url:'OSXversion_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'OSXversion_files/stroke_9.png'},{rect:new IWRect(1,-1,722,2),url:'OSXversion_files/stroke_10.png'},{rect:new IWRect(723,-1,2,2),url:'OSXversion_files/stroke_11.png'},{rect:new IWRect(723,1,2,35),url:'OSXversion_files/stroke_12.png'},{rect:new IWRect(723,36,2,2),url:'OSXversion_files/stroke_13.png'},{rect:new IWRect(1,36,722,2),url:'OSXversion_files/stroke_14.png'},{rect:new IWRect(-1,36,2,2),url:'OSXversion_files/stroke_15.png'}],new IWSize(724,37)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,65),url:'OSXversion_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'OSXversion_files/stroke_1.png'},{rect:new IWRect(1,-1,769,2),url:'OSXversion_files/stroke_2.png'},{rect:new IWRect(770,-1,2,2),url:'OSXversion_files/stroke_3.png'},{rect:new IWRect(770,1,2,65),url:'OSXversion_files/stroke_4.png'},{rect:new IWRect(770,66,2,2),url:'OSXversion_files/stroke_5.png'},{rect:new IWRect(1,66,769,2),url:'OSXversion_files/stroke_6.png'},{rect:new IWRect(-1,66,2,2),url:'OSXversion_files/stroke_7.png'}],new IWSize(771,67)),stroke_4:new IWStrokeParts([{rect:new IWRect(-1,1,2,245),url:'OSXversion_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'OSXversion_files/stroke_25.png'},{rect:new IWRect(1,-1,487,2),url:'OSXversion_files/stroke_26.png'},{rect:new IWRect(488,-1,2,2),url:'OSXversion_files/stroke_27.png'},{rect:new IWRect(488,1,2,245),url:'OSXversion_files/stroke_28.png'},{rect:new IWRect(488,246,2,2),url:'OSXversion_files/stroke_29.png'},{rect:new IWRect(1,246,487,2),url:'OSXversion_files/stroke_30.png'},{rect:new IWRect(-1,246,2,2),url:'OSXversion_files/stroke_31.png'}],new IWSize(489,247)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,37),url:'OSXversion_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'OSXversion_files/stroke_17.png'},{rect:new IWRect(1,-1,770,2),url:'OSXversion_files/stroke_18.png'},{rect:new IWRect(771,-1,2,2),url:'OSXversion_files/stroke_19.png'},{rect:new IWRect(771,1,2,37),url:'OSXversion_files/stroke_20.png'},{rect:new IWRect(771,38,2,2),url:'OSXversion_files/stroke_21.png'},{rect:new IWRect(1,38,770,2),url:'OSXversion_files/stroke_22.png'},{rect:new IWRect(-1,38,2,2),url:'OSXversion_files/stroke_23.png'}],new IWSize(772,39)),stroke_3:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('OSXversion_files/OSXversionMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');applyEffects()}
