// Created by iWeb 3.0.4 local-build-20130907

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,35),url:'MigrateLion.N_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'MigrateLion.N_files/stroke_17.png'},{rect:new IWRect(1,-1,770,2),url:'MigrateLion.N_files/stroke_18.png'},{rect:new IWRect(771,-1,2,2),url:'MigrateLion.N_files/stroke_19.png'},{rect:new IWRect(771,1,2,35),url:'MigrateLion.N_files/stroke_20.png'},{rect:new IWRect(771,36,2,2),url:'MigrateLion.N_files/stroke_21.png'},{rect:new IWRect(1,36,770,2),url:'MigrateLion.N_files/stroke_22.png'},{rect:new IWRect(-1,36,2,2),url:'MigrateLion.N_files/stroke_23.png'}],new IWSize(772,37)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,65),url:'MigrateLion.N_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'MigrateLion.N_files/stroke_1.png'},{rect:new IWRect(1,-1,769,2),url:'MigrateLion.N_files/stroke_2.png'},{rect:new IWRect(770,-1,2,2),url:'MigrateLion.N_files/stroke_3.png'},{rect:new IWRect(770,1,2,65),url:'MigrateLion.N_files/stroke_4.png'},{rect:new IWRect(770,66,2,2),url:'MigrateLion.N_files/stroke_5.png'},{rect:new IWRect(1,66,769,2),url:'MigrateLion.N_files/stroke_6.png'},{rect:new IWRect(-1,66,2,2),url:'MigrateLion.N_files/stroke_7.png'}],new IWSize(771,67)),stroke_3:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,35),url:'MigrateLion.N_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'MigrateLion.N_files/stroke_9.png'},{rect:new IWRect(1,-1,770,2),url:'MigrateLion.N_files/stroke_10.png'},{rect:new IWRect(771,-1,2,2),url:'MigrateLion.N_files/stroke_11.png'},{rect:new IWRect(771,1,2,35),url:'MigrateLion.N_files/stroke_12.png'},{rect:new IWRect(771,36,2,2),url:'MigrateLion.N_files/stroke_13.png'},{rect:new IWRect(1,36,770,2),url:'MigrateLion.N_files/stroke_14.png'},{rect:new IWRect(-1,36,2,2),url:'MigrateLion.N_files/stroke_15.png'}],new IWSize(772,37))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('MigrateLion.N_files/MigrateLion.NMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');applyEffects()}
