// Created by iWeb 3.0.4 local-build-20130606

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,28),url:'Troubleshooting_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Troubleshooting_files/stroke_9.png'},{rect:new IWRect(1,-1,716,2),url:'Troubleshooting_files/stroke_10.png'},{rect:new IWRect(717,-1,2,2),url:'Troubleshooting_files/stroke_11.png'},{rect:new IWRect(717,1,2,28),url:'Troubleshooting_files/stroke_12.png'},{rect:new IWRect(717,29,2,2),url:'Troubleshooting_files/stroke_13.png'},{rect:new IWRect(1,29,716,2),url:'Troubleshooting_files/stroke_14.png'},{rect:new IWRect(-1,29,2,2),url:'Troubleshooting_files/stroke_15.png'}],new IWSize(718,30)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,39),url:'Troubleshooting_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Troubleshooting_files/stroke_17.png'},{rect:new IWRect(1,-1,761,2),url:'Troubleshooting_files/stroke_18.png'},{rect:new IWRect(762,-1,2,2),url:'Troubleshooting_files/stroke_19.png'},{rect:new IWRect(762,1,2,39),url:'Troubleshooting_files/stroke_20.png'},{rect:new IWRect(762,40,2,2),url:'Troubleshooting_files/stroke_21.png'},{rect:new IWRect(1,40,761,2),url:'Troubleshooting_files/stroke_22.png'},{rect:new IWRect(-1,40,2,2),url:'Troubleshooting_files/stroke_23.png'}],new IWSize(763,41)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,65),url:'Troubleshooting_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Troubleshooting_files/stroke_1.png'},{rect:new IWRect(1,-1,769,2),url:'Troubleshooting_files/stroke_2.png'},{rect:new IWRect(770,-1,2,2),url:'Troubleshooting_files/stroke_3.png'},{rect:new IWRect(770,1,2,65),url:'Troubleshooting_files/stroke_4.png'},{rect:new IWRect(770,66,2,2),url:'Troubleshooting_files/stroke_5.png'},{rect:new IWRect(1,66,769,2),url:'Troubleshooting_files/stroke_6.png'},{rect:new IWRect(-1,66,2,2),url:'Troubleshooting_files/stroke_7.png'}],new IWSize(771,67))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Troubleshooting_files/TroubleshootingMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id6');applyEffects()}
